name: mywonderbird
description: MyWonderbird travel app
version: 0.4.30+58

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^2.0.1
  provider: ^4.1.2
  http: ^0.13.0
  timeago: ^2.0.26
  receive_sharing_intent: ^1.4.0+2
  exif: ^1.0.3
  flutter_dotenv: ^2.1.0
  location: ^4.1.1
  uuid: ^3.0.1
  shared_preferences: ">=0.5.7+3 <2.0.0"
  get_it: ^4.0.2
  email_validator: "^1.0.0"
  url_launcher: "^6.0.2"
  uni_links: "^0.4.0"
  flutter_full_pdf_viewer: ^1.0.6
  sentry: ^4.0.6
  photo_manager: ^0.5.7
  transparent_image: ^1.0.0
  photo_view: ^0.9.2
  characters: ^1.0.0
  image: ^3.0.1
  percent_indicator: ^2.1.5
  flutter_icons: ^1.1.0
  image_picker: ^0.7.2+1
  crop: ^0.4.1
  vector_math: ^2.0.8
  numberpicker: ^1.2.1
  map_launcher: 1.1.3+1
  quiver: ^2.1.3
  firebase_analytics: ^7.1.1
  firebase_core: 1.0.1
  im_stepper: ^0.1.2+6
  story_view: ^0.12.5
  permission_handler: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
    - images/mywonderbird-travel.jpg
    - images/logo.png
    - images/logo@025x.png
    - images/logo-inverse.png
    - images/logo-inverse@025x.png
    - images/coming-soon.png
    - images/congratulations.png
    - images/onboarding/
    - images/feedback/
    - images/filters/
    - images/questionnaire/
    - env/
