name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.28+1
  provider: ^4.1.2
  http: ^0.12.1
  timeago: ^2.0.26
  receive_sharing_intent: ^1.4.0+2
  exif: ^1.0.3
  flutter_dotenv: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family:  CustomIcons
        fonts:
          - asset: fonts/CustomIcons.ttf
  assets:
    - .env